### ISSUE TITLE
Wawacat

### ISSUE THREAD

**Issue by SK-Fast** [CastillaSBC/Monorepo#1]
![wawacat](https://user-images.githubusercontent.com/60780448/167304759-0234bab7-d522-4eeb-884b-e4eb3d81d759.png)

**Comment by stampe99** [comment]
![i](https://tenor.com/view/ip-grabber-ip-grabber-thanos-gif-21846609)

**Comment by stampe99** [comment]
![trol](https://media.discordapp.net/attachments/922860130826076220/972092910625509376/Screenshot_2022-05-06-18-07-39-12.jpg)
